/*
 * This source file was generated by the Gradle 'init' task
 */
package wigglecontroller;

public class App
{
    public static void main(String[] args)
    {
        Window window = new Window();

        window.show();
    }
}
